### ISSUE TITLE
'zip' is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by eric-unc** [onsmith/comp426-cli#5]
![image](https://user-images.githubusercontent.com/54514192/96745444-23b3b700-1394-11eb-997a-3ccd6792c4ad.png)

As seen above, the script manages to pull through anyway, but I'm tired of seeing this error message. (This is, I assume, a Windows-specific issue since I'm using PowerShell)

**Comment by cgbur** [comment]
Out of our control. We are using a 3rd party zipping library [bestzip](npmjs.com/package/bestzip). If it really bothers you take it up with them.

**Comment by eric-unc** [comment]
Looks like [this was fixed already](https://github.com/nfriedly/node-bestzip/pull/33). I humbly request you update the libraries you're using.
